name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go-dep
        run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: CI
        run: make deploy
        env:
        GOPATH: /home/runner/work/go-aws-arch/go-aws-arch
